services:
  - type: web
    name: deep-shiva
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_VERSION
        sync: false
      - key: AZURE_GPT_DEPLOYMENT
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true